name: Python Tests and Linting

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest ruff black
          pip install -e .

      - name: Make calc.py executable
        run: chmod +x calc.py

      - name: Lint with Ruff
        run: |
          ruff check .

      - name: Format check with Black
        run: |
          black --check .

      - name: Test core functions
        run: |
          pytest -v tests/test_llodlloq.py

      - name: Test command-line tool
        run: |
          pytest -v tests/test_calc.py

      - name: Test Streamlit app
        run: |
          pytest -v tests/test_app.py
